from dataclasses import dataclass
from homeassistant.components.sensor import (
    SensorDeviceClass,
    SensorEntityDescription,
    SensorStateClass,
)
from homeassistant.const import (
    PERCENTAGE,
    UnitOfElectricCurrent,
    UnitOfElectricPotential,
    UnitOfEnergy,
    UnitOfFrequency,
    UnitOfPower,
    UnitOfTemperature,
)

DOMAIN = "selfa"
DEFAULT_HOST = "192.168.1.1"
DEFAULT_PORT = 5743
DEFAULT_SLAVE = 252
DEFAULT_SCAN_INTERVAL = 5


@dataclass(frozen=True, kw_only=True)
class SelfaSensorDescription(SensorEntityDescription):
    register: int = 0
    data_type: str = "uint16"  # uint16, int16, uint32, int32
    scale: float = 1.0


SENSORS: tuple[SelfaSensorDescription, ...] = (
    # --- Inverter ---
    SelfaSensorDescription(
        key="inverter_status",
        name="Inverter Status",
        register=10105,
        data_type="uint16",
    ),
    SelfaSensorDescription(
        key="inverter_ac_power",
        name="Inverter AC Power",
        register=11016,
        data_type="int32",
        scale=0.001,
        native_unit_of_measurement=UnitOfPower.KILO_WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SelfaSensorDescription(
        key="inverter_temp",
        name="Inverter Temperature",
        register=11032,
        data_type="int16",
        scale=0.1,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SelfaSensorDescription(
        key="energy_today",
        name="Energy Today",
        register=11018,
        data_type="uint32",
        scale=0.1,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    SelfaSensorDescription(
        key="energy_total",
        name="Energy Total",
        register=11020,
        data_type="uint32",
        scale=0.1,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    # --- Grid ---
    SelfaSensorDescription(
        key="grid_meter_power",
        name="Grid Meter Power",
        register=11000,
        data_type="int32",
        scale=0.001,
        native_unit_of_measurement=UnitOfPower.KILO_WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SelfaSensorDescription(
        key="grid_voltage",
        name="Grid Voltage",
        register=11009,
        data_type="uint16",
        scale=0.1,
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SelfaSensorDescription(
        key="grid_frequency",
        name="Grid Frequency",
        register=11015,
        data_type="uint16",
        scale=0.01,
        native_unit_of_measurement=UnitOfFrequency.HERTZ,
        device_class=SensorDeviceClass.FREQUENCY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SelfaSensorDescription(
        key="daily_grid_injection",
        name="Daily Grid Injection",
        register=31000,
        data_type="uint16",
        scale=0.1,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    SelfaSensorDescription(
        key="daily_grid_purchase",
        name="Daily Grid Purchase",
        register=31001,
        data_type="uint16",
        scale=0.1,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    SelfaSensorDescription(
        key="total_grid_injection",
        name="Total Grid Injection",
        register=31102,
        data_type="uint32",
        scale=0.1,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    SelfaSensorDescription(
        key="total_grid_purchase",
        name="Total Grid Purchase",
        register=31104,
        data_type="uint32",
        scale=0.1,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    # --- PV ---
    SelfaSensorDescription(
        key="pv_input_power",
        name="PV Input Power",
        register=11028,
        data_type="uint32",
        scale=0.001,
        native_unit_of_measurement=UnitOfPower.KILO_WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SelfaSensorDescription(
        key="pv1_power",
        name="PV1 Power",
        register=11062,
        data_type="uint32",
        scale=0.001,
        native_unit_of_measurement=UnitOfPower.KILO_WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SelfaSensorDescription(
        key="pv2_power",
        name="PV2 Power",
        register=11064,
        data_type="uint32",
        scale=0.001,
        native_unit_of_measurement=UnitOfPower.KILO_WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SelfaSensorDescription(
        key="pv1_voltage",
        name="PV1 Voltage",
        register=11038,
        data_type="uint16",
        scale=0.1,
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SelfaSensorDescription(
        key="pv2_voltage",
        name="PV2 Voltage",
        register=11040,
        data_type="uint16",
        scale=0.1,
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SelfaSensorDescription(
        key="daily_pv_generation",
        name="Daily PV Generation",
        register=31005,
        data_type="uint16",
        scale=0.1,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    SelfaSensorDescription(
        key="total_pv_generation",
        name="Total PV Generation",
        register=31112,
        data_type="uint32",
        scale=0.1,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    # --- Battery ---
    SelfaSensorDescription(
        key="battery_power",
        name="Battery Power",
        register=30258,
        data_type="int32",
        scale=0.001,
        native_unit_of_measurement=UnitOfPower.KILO_WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SelfaSensorDescription(
        key="battery_voltage",
        name="Battery Voltage",
        register=30254,
        data_type="uint16",
        scale=0.1,
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SelfaSensorDescription(
        key="battery_current",
        name="Battery Current",
        register=30255,
        data_type="int16",
        scale=0.1,
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SelfaSensorDescription(
        key="battery_soc",
        name="Battery SOC",
        register=33000,
        data_type="uint16",
        scale=0.01,
        native_unit_of_measurement=PERCENTAGE,
        device_class=SensorDeviceClass.BATTERY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SelfaSensorDescription(
        key="battery_soh",
        name="Battery SOH",
        register=33001,
        data_type="uint16",
        scale=0.01,
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SelfaSensorDescription(
        key="bms_temperature",
        name="BMS Temperature",
        register=33003,
        data_type="uint16",
        scale=0.1,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SelfaSensorDescription(
        key="daily_battery_charge",
        name="Daily Battery Charge",
        register=31003,
        data_type="uint16",
        scale=0.1,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    SelfaSensorDescription(
        key="daily_battery_discharge",
        name="Daily Battery Discharge",
        register=31004,
        data_type="uint16",
        scale=0.1,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    SelfaSensorDescription(
        key="daily_load_consumption",
        name="Daily Load Consumption",
        register=31006,
        data_type="uint16",
        scale=0.1,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
)
