from dataclasses import dataclass
from homeassistant.components.sensor import (
    SensorDeviceClass,
    SensorEntityDescription,
    SensorStateClass,
)
from homeassistant.helpers.entity import EntityCategory
from homeassistant.const import (
    PERCENTAGE,
    UnitOfElectricCurrent,
    UnitOfElectricPotential,
    UnitOfEnergy,
    UnitOfFrequency,
    UnitOfPower,
    UnitOfTemperature,
)

DOMAIN = "selfa"
DEFAULT_HOST = "192.168.1.1"
DEFAULT_PORT = 5743
DEFAULT_SLAVE = 252
DEFAULT_SCAN_INTERVAL = 5
CONF_EXPERT_MODE = "expert_mode"
CONF_BREAKER = "breaker_type"

# Maximum import power (kVA) per breaker rating (3-phase, 400 V)
BREAKER_LIMITS: dict[str, float] = {
    "16A": 11.0,
    "20A": 13.8,
    "32A": 22.0,
}

WORKING_MODES: dict[str, int] = {
    "General":            0x0101,
    "Economic":           0x0102,
    "UPS":                0x0103,
    "Off-grid":           0x0200,
    "EMS AC Control":     0x0301,
    "EMS General":        0x0302,
    "EMS Battery Control":0x0303,
    "EMS Off-grid":       0x0404,
}


@dataclass(frozen=True, kw_only=True)
class SelfaSensorDescription(SensorEntityDescription):
    register: int = 0
    data_type: str = "uint16"  # uint16, int16, uint32, int32
    scale: float = 1.0
    value_map: dict[int, str] | None = None


SENSORS: tuple[SelfaSensorDescription, ...] = (
    # --- Inverter ---
    SelfaSensorDescription(
        key="serial_number",
        name="Serial Number",
        register=0,  # virtual — value injected by coordinator
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    SelfaSensorDescription(
        key="crc_error_count",
        name="CRC Error Count",
        register=0,  # virtual — value injected by coordinator
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    SelfaSensorDescription(
        key="breaker_type",
        name="Breaker Type",
        register=0,  # virtual — value injected by coordinator
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    SelfaSensorDescription(
        key="max_import_kva",
        name="Max Import Power",
        register=0,  # virtual — value injected by coordinator
        native_unit_of_measurement="kVA",
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    SelfaSensorDescription(
        key="inverter_status",
        name="Inverter Status",
        register=10105,
        data_type="uint16",
        value_map={
            0: "Waiting for grid",
            1: "Self-checking",
            2: "On-grid",
            3: "Fault",
            4: "Firmware upgrade",
            5: "Off-grid",
        },
    ),
    SelfaSensorDescription(
        key="inverter_ac_power",
        name="Inverter AC Power",
        register=11016,
        data_type="int32",
        scale=0.001,
        native_unit_of_measurement=UnitOfPower.KILO_WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SelfaSensorDescription(
        key="home_power",
        name="Home Power",
        register=0,  # virtual — computed by coordinator: PV + Battery - Grid
        native_unit_of_measurement=UnitOfPower.KILO_WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SelfaSensorDescription(
        key="inverter_temp",
        name="Inverter Temperature",
        register=11032,
        data_type="int16",
        scale=0.1,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SelfaSensorDescription(
        key="energy_today",
        name="Energy Today",
        register=11018,
        data_type="uint32",
        scale=0.1,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    SelfaSensorDescription(
        key="energy_total",
        name="Energy Total",
        register=11020,
        data_type="uint32",
        scale=0.1,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    # --- Grid ---
    SelfaSensorDescription(
        key="grid_meter_power",
        name="Grid Power",
        register=11000,
        data_type="int32",
        scale=0.001,
        native_unit_of_measurement=UnitOfPower.KILO_WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SelfaSensorDescription(
        key="l1_voltage",
        name="L1 Voltage",
        register=11009,
        data_type="uint16",
        scale=0.1,
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SelfaSensorDescription(
        key="l1_current",
        name="L1 Current",
        register=11010,
        data_type="uint16",
        scale=0.1,
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SelfaSensorDescription(
        key="l2_voltage",
        name="L2 Voltage",
        register=11011,
        data_type="uint16",
        scale=0.1,
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SelfaSensorDescription(
        key="l2_current",
        name="L2 Current",
        register=11012,
        data_type="uint16",
        scale=0.1,
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SelfaSensorDescription(
        key="l3_voltage",
        name="L3 Voltage",
        register=11013,
        data_type="uint16",
        scale=0.1,
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SelfaSensorDescription(
        key="l3_current",
        name="L3 Current",
        register=11014,
        data_type="uint16",
        scale=0.1,
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SelfaSensorDescription(
        key="grid_frequency",
        name="Grid Frequency",
        register=11015,
        data_type="uint16",
        scale=0.01,
        native_unit_of_measurement=UnitOfFrequency.HERTZ,
        device_class=SensorDeviceClass.FREQUENCY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SelfaSensorDescription(
        key="daily_grid_injection",
        name="Energy Exported to Grid Today",
        register=31000,
        data_type="uint16",
        scale=0.1,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL,
    ),
    SelfaSensorDescription(
        key="daily_grid_purchase",
        name="Energy Imported from Grid Today",
        register=31001,
        data_type="uint16",
        scale=0.1,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL,
    ),
    SelfaSensorDescription(
        key="total_grid_injection",
        name="Energy Exported to Grid",
        register=31102,
        data_type="uint32",
        scale=0.1,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    SelfaSensorDescription(
        key="total_grid_purchase",
        name="Energy Imported from Grid",
        register=31104,
        data_type="uint32",
        scale=0.1,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    # --- PV ---
    SelfaSensorDescription(
        key="pv_input_power",
        name="Solar Power",
        register=11028,
        data_type="uint32",
        scale=0.001,
        native_unit_of_measurement=UnitOfPower.KILO_WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SelfaSensorDescription(
        key="pv1_power",
        name="PV1 Power",
        register=11062,
        data_type="uint32",
        scale=0.001,
        native_unit_of_measurement=UnitOfPower.KILO_WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SelfaSensorDescription(
        key="pv2_power",
        name="PV2 Power",
        register=11064,
        data_type="uint32",
        scale=0.001,
        native_unit_of_measurement=UnitOfPower.KILO_WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SelfaSensorDescription(
        key="pv1_voltage",
        name="PV1 Voltage",
        register=11038,
        data_type="uint16",
        scale=0.1,
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SelfaSensorDescription(
        key="pv2_voltage",
        name="PV2 Voltage",
        register=11040,
        data_type="uint16",
        scale=0.1,
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SelfaSensorDescription(
        key="daily_pv_generation",
        name="Solar Energy Today",
        register=31005,
        data_type="uint16",
        scale=0.1,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL,
    ),
    SelfaSensorDescription(
        key="total_pv_generation",
        name="Solar Energy",
        register=31112,
        data_type="uint32",
        scale=0.1,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    # --- Battery ---
    SelfaSensorDescription(
        key="battery_power",
        name="Battery Power",
        register=30258,
        data_type="int32",
        scale=0.001,
        native_unit_of_measurement=UnitOfPower.KILO_WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SelfaSensorDescription(
        key="battery_voltage",
        name="Battery Voltage",
        register=30254,
        data_type="uint16",
        scale=0.1,
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SelfaSensorDescription(
        key="battery_current",
        name="Battery Current",
        register=30255,
        data_type="int16",
        scale=0.1,
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SelfaSensorDescription(
        key="battery_soc",
        name="Battery SOC",
        register=33000,
        data_type="uint16",
        scale=0.01,
        native_unit_of_measurement=PERCENTAGE,
        device_class=SensorDeviceClass.BATTERY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SelfaSensorDescription(
        key="battery_soh",
        name="Battery SOH",
        register=33001,
        data_type="uint16",
        scale=0.01,
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SelfaSensorDescription(
        key="battery_power_sched",
        name="Battery Power Scheduling",
        register=50207,
        data_type="int16",
        scale=0.01,
        native_unit_of_measurement=UnitOfPower.KILO_WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SelfaSensorDescription(
        key="working_mode",
        name="Working Mode",
        register=50000,
        data_type="uint16",
        value_map={
            0x0101: "General",
            0x0102: "Economic",
            0x0103: "UPS",
            0x0200: "Off-grid",
            0x0301: "EMS AC Control",
            0x0302: "EMS General",
            0x0303: "EMS Battery Control",
            0x0404: "EMS Off-grid",
        },
    ),
    SelfaSensorDescription(
        key="battery_brand",
        name="Battery Brand",
        register=52500,
        data_type="uint16",
        entity_category=EntityCategory.DIAGNOSTIC,
        value_map={
            2: "EMS",
            10: "Wattsonic Li-HV",
            11: "AOBOET",
            12: "DYNESS",
            13: "Pylon",
            14: "Soluna",
            15: "SheenPlus",
            16: "WECO",
        },
    ),
    SelfaSensorDescription(
        key="bms_status",
        name="BMS Status",
        register=33002,
        data_type="uint16",
        value_map={0: "sleep", 1: "charging", 2: "discharging", 3: "standby", 4: "fault"},
    ),
    SelfaSensorDescription(
        key="bms_temperature",
        name="BMS Temperature",
        register=33003,
        data_type="uint16",
        scale=0.1,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SelfaSensorDescription(
        key="daily_battery_charge",
        name="Energy Charged into Battery Today",
        register=31003,
        data_type="uint16",
        scale=0.1,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL,
    ),
    SelfaSensorDescription(
        key="daily_battery_discharge",
        name="Energy Discharged from Battery Today",
        register=31004,
        data_type="uint16",
        scale=0.1,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL,
    ),
    SelfaSensorDescription(
        key="daily_load_consumption",
        name="Home Energy Today",
        register=31006,
        data_type="uint16",
        scale=0.1,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL,
    ),
    SelfaSensorDescription(
        key="total_battery_charge",
        name="Energy Charged into Battery",
        register=31108,
        data_type="uint32",
        scale=0.1,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    SelfaSensorDescription(
        key="total_battery_discharge",
        name="Energy Discharged from Battery",
        register=31110,
        data_type="uint32",
        scale=0.1,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    SelfaSensorDescription(
        key="total_load_consumption",
        name="Home Energy",
        register=31114,
        data_type="uint32",
        scale=0.1,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
)
